# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.

relative_permalinks: false

# Setup
title:               퉤니포 서연쓰 
tagline:             'DataArtist'
description:         '안녕하세요 전서연입니다.'
url:                 'https://shanny924.github.io'
baseurl:             
paginate:            

# About/contact
author:
  name:              Mark Otto
  url:               https://twitter.com/mdo
  email:             markdotto@gmail.com

# Custom vars
version:             1.0.0
